### ISSUE TITLE
SDK Update from 1.10.4 to 1.10.6

### ISSUE THREAD

**Issue by bmwGTR** [JAGFx/ets2-dashboard-skin#33]
Hi,

please (if you have the time) update the SDK from 1.10.4 to 1.10.6. 
In 1.10.6 the bug for the remaining time is fixed, currently I have everytime to remove one day from the remaining time (even on "normal" jobs).

Thank you.

**Comment by JAGFx** [comment]
I,

It's planned. But I need to end some feature before. 
I'm do it quickly as I can :D 

Thanks for your interest!

**Comment by JAGFx** [comment]
Work good with standard job, but totally crazy with job taken from WOT

**Comment by bmwGTR** [comment]
Hi,

tested the current release (1.4.0) with the SDK version 1.10.6 - still got the wrong remaning delivery time on the dashboard (1 day more as still remaning).

Thank you for your hard work!

**Comment by JAGFx** [comment]
Hi.

Yes, in my investigation I see that it might miss the data about the job remaining date.

The job delivery time was good. But not with WOT job.
I'm in discussions with the owner of the Telemetry server to find a way ^^.

**Comment by JAGFx** [comment]
@bmwGTR  Can you tell me what's are your setting for the timezone on ETS ?

**Comment by JAGFx** [comment]
@bmwGTR 

After a while investigation, I've found an explanation:
All date and time from ETS (and ATS too) are set on GMT+0
SCS added the possibility to display all date and time with timezone. (Options > Jouability > Time zone > Full)

But, from the SDK, I can't know whitch timezone are used for this dates and times.
If you disable this feature on ETS (or ATS), the date and time for the job due date and the job remaining date time was correct.
But if you enable it, they can be correct or not. It's depend of the country crossed, the country destination and  / or the country of departure.

I've make a fix to be correct without time zone (a.k.a With time zone option disabled on ETS or ATS). But I can't garantee a dates and times with a correct time zone if this option was enabled
