### ISSUE TITLE
Telemetry Desync on Mobile

### ISSUE THREAD

**Issue by RunnyPilot** [JAGFx/ets2-dashboard-skin#41]
**Describe the bug**
What happens is, at first, the telemetry syncs up perfectly well. Extremely responsive but after some time, it suddenly becomes desynchronized. Refreshing the browser fixed my issue temporarily.

**Expected behavior**
I expected the app to refresh itself but I had to do it myself.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Not used on PC
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Browser: Tested on Chrome, Edge and Brave. All the same.
 - Version: Latest

**Additional context**
- Skin name: JAGFx
- Dashboard version: v1.4.2
- SCS Telemetry version: v1.10.4
- Node version: node14

**Comment by JAGFx** [comment]
@RunnyPilot Thank for your report.

I've see the same issue. I think is the "no sleep" dependencie that's cause this issues.

I'm plan to change to another one.

**Comment by JAGFx** [comment]
@RunnyPilot  Great news ! It will be fixed on the next release.
No desync data. But, if you have a freeze, you can touch the screen.
I don't know (yet) why, but it's work.
