### ISSUE TITLE
Next rest time and reamining time bad

### ISSUE THREAD

**Issue by kolarek-dk0** [JAGFx/ets2-dashboard-skin#46]
**Describe the bug**
Next rest time and reamining time is displayed bad.

**Expected behavior**
Next rest time displayed more time (1h+) and reamining time too (+1d and 1h)

**Screenshots**
![Bez názvu](https://user-images.githubusercontent.com/74896986/99941045-a3ef8280-2d6d-11eb-9d4b-ed48dd1a74e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 87.0.664.41

**Smartphone (please complete the following information):**
Do not use smartphone applicable

**Additional context**
- Skin name: JAGFx
- Dashboard version:  v1.4.3
- SCS Telemetry version: 1.10.6
- Node version: node14

**Comment by JAGFx** [comment]
@kolarek-dk0 Hi.

Unfortunately, I can't do anything for this issue for this moment. 
You can found the full explanation on this issue. 

https://github.com/JAGFx/ets2-dashboard-skin/issues/33#issuecomment-725514001

Tell me if you have any others questions.
