### ISSUE TITLE
Job Information Disappears when using Eurotunnel

### ISSUE THREAD

**Issue by Hi-ImKyle** [JAGFx/ets2-dashboard-skin#47]
**Describe the bug**
Changing location via the ferry or Eurotunnel, let's say from Dover UK to Calais France causes the UI to lose the job information. The distance on the web UI does update and is correct, just the rest of the job information is lost.

**Expected behaviour**
For it to keep the job info

**Screenshots**
![In Game](https://user-images.githubusercontent.com/25551312/100809311-c0568380-342d-11eb-9dff-e355ed5f716f.png)
![Web UI](https://user-images.githubusercontent.com/25551312/100809350-d8c69e00-342d-11eb-9c8d-364f6c37daf1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 10
 - Browser: Chrome, Edge, Firefox
 - Version: N/A

**Additional context**
- Skin name: JAGFx
- Dashboard version: 1.4.3
- SCS Telemetry version: 1.16
- Node version: Node 13.11.0

**Additional information**
- Reopening the node app does not fetch the job info.
- Seems to stay lost till the end of the job

**Comment by JAGFx** [comment]
Hi @Hi-ImKyle 

Unfortunately, I can't fix this. Datas are missing after the crossing through the ferry. It's a SCS SDK issue.
I'm gonna contact the SCS SDK owner to know more about it and keep this issue up to date.

Sorry for it...

**Comment by Hi-ImKyle** [comment]
Surely there's a job completed/cancelled event? Just hold the data and don't remove it unless the job is cancelled? Sorry if this is not how it works, just trying to think of a way that might. But if not and we need to wait then it's a small bug imo, I can deal with it.

**Comment by JAGFx** [comment]
@Hi-ImKyle 

On this project, it's not work like you think.
All data shown are in real time. Navigation datas,  truck data, job data, trailers data and other are in real time.
So, if the real time data was empty, they will shown empty too.

When an issue occurred about it, I need to check the data from the provider to know if it's a provider issue or if the game can't provide them.

It's not planned to store any real time data for this project

**Comment by Hi-ImKyle** [comment]
Righto! Guess we have to wait. I'll be looking forward to the time it's fixed :)

**Comment by JAGFx** [comment]
Hi @Hi-ImKyle !

Great news: The SDK have fixed this issue. I'ill get it and if it's work properly, it will be corrected on the next release.

**Comment by JAGFx** [comment]
It's fixed !
