### ISSUE TITLE
Damage Inaccurate

### ISSUE THREAD

**Issue by daywalker78** [JAGFx/ets2-dashboard-skin#55]
Damage of Truck and Trailer on the dashboard is a lot lower than in game.

**Comment by JAGFx** [comment]
@daywalker78 Can you tell me what's are your damage reference on the game ?

Currently, on the JAGFx skin, the value displayed are an average of the following damages values:

- cabin
- chassis
- engine
- transmission
- wheels

And it's was correct in regard of the ETS2 "Damage evaluation" panel.

**Comment by JAGFx** [comment]
The value displayed on the route advisor match with the frame body damage.
Same for the trailer.

**Comment by JAGFx** [comment]
On option was added. It's allow you to choose between:

- The average with values of the `Damage diagnostic`
- The value of the `Route advisor`
