### ISSUE TITLE
trying to host my own promod files  snce i cannot get any to work

### ISSUE THREAD

**Issue by jpoblocki77** [JAGFx/ets2-dashboard-skin#69]
{
  "error": {
    "message": "Network Error",
    "name": "Error",
    "stack": "Error: Network Error\n    at createError (webpack:///./node_modules/axios/lib/core/createError.js?:16:15)\n    at XMLHttpRequest.handleError (webpack:///./node_modules/axios/lib/adapters/xhr.js?:84:14)",
    "config": {
      "url": "/config",
      "method": "post",
      "data": "{\"general_region\":\"eu\",\"general_refresh_rate\":15,\"general_skin_on_load\":\"Maps\",\"general_unit_auto\":false,\"general_h-shift-layout\":\"h-shifter\",\"unit_weight\":\"kg\",\"unit_length\":\"m\",\"unit_degrees\":\"C\",\"unit_consumption\":\"lpkm\",\"unit_volume\":\"l\",\"unit_pressure\":\"psi\",\"unit_speed\":\"kph\",\"unit_currency\":\"EUR\",\"general_job_remaining\":\"due_date\",\"jagfx_elements_right_oilTemperature\":\"true\",\"jagfx_elements_right_brakesTemperature\":\"true\",\"jagfx_elements_right_brakesAirPressure\":\"true\",\"jagfx_elements_right_fuel\":\"true\",\"jagfx_elements_right_fuelConsumption\":\"true\",\"jagfx_elements_right_cruiseControl\":\"true\",\"jagfx_elements_right_waterTemperature\":\"true\",\"jagfx_elements_right_batteryVoltage\":\"false\",\"jagfx_elements_mid_top_retarder\":\"true\",\"jagfx_elements_mid_top_parkingBrake\":\"true\",\"jagfx_elements_mid_top_beamHigh\":\"true\",\"jagfx_elements_mid_top_beamLow\":\"true\",\"jagfx_elements_mid_top_beacon\":\"false\",\"jagfx_elements_mid_bottom_rpm\":\"true\",\"jagfx_elements_mid_bottom_fuel\":\"true\",\"jagfx_elements_mid_bottom_speedLimit\":\"true\",\"jagfx_elements_right_restStop\":\"false\",\"jagfx_elements_mid_bottom_blinker_turn\":\"true\",\"events_truck.refuel\":true,\"events_truck.damage\":true,\"events_truck.park\":true,\"events_truck.engine\":true,\"events_truck.electric\":true,\"events_truck.emergency\":true,\"events_truck.warning\":true,\"events_truck.cruise-control-decrease\":true,\"events_truck.cruise-control-increase\":true,\"events_truck.cruise-control\":true,\"events_trailers.damage\":true,\"events_trailers.coupling\":true,\"events_navigation.speed-limit\":true,\"events_job.started\":true,\"events_job.finished\":true,\"events_job.delivered\":true,\"events_job.cancelled\":true,\"events_game.refuel-payed\":true,\"events_game.train\":true,\"events_game.ferry\":true,\"events_game.tollgate\":true,\"events_game.fine\":true,\"events_game.pause\":true,\"maps_elements_eta\":true,\"maps_elements_speedAndGear\":true,\"maps_elements_mapControls\":true,\"maps_elements_speedLimit\":true,\"maps_map_type\":\"mod\",\"maps_map_tilesRemotePath\":\"http://localhost:8081\",\"maps_map_activeMap\":null,\"maps_map_navigationRemaining\":\"remaining_date\",\"maps_map_tilesVersion\":\"latest\",\"general_damage_accurate\":\"damage-diagnostic\"}",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json;charset=utf-8"
      },
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1
    }
  },
  "code": "CONFIG_SAVE_FAILED"
}

**Comment by JAGFx** [comment]
Hi @jpoblocki77 ,

Can you share me the version used ?

You can check the following thing:

- Have you a file named `config.ets2-dashboard-skin.json` at the same folder of this app (with `*.exe`) ?
- Have you a correct asses write on this file ?
- This file are not corrupted ?
- This file are not empty ?
- This file contain a valid json data ? (Copy and past all content on this [website](https://jsonformatter.curiousconcept.com/#))

**Comment by JAGFx** [comment]
@jpoblocki77 Please read again this [readme](https://github.com/JAGFx/ets2-dashboard-skin/blob/master/doc/MAP.md#self-hosting). It's was been updated with a correct file structure.
