### ISSUE TITLE
The due date or remaining date on the left does not display

### ISSUE THREAD

**Issue by sanekaze** [JAGFx/ets2-dashboard-skin#71]
**Describe the bug**
The due date or remaining date on the left does not display on the JAGFx dashboard but only show N/A

**Expected behavior**
Regardless of the setting on the estimated delivery date or the time remaining for delivery, the indicator displays N / A whether on browser from the computer or from the tablet

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 dernière version à jour
 - Browser [e.g. chrome, safari] Vivaldi 4.0.2312.41 (base chrome)

**Smartphone (please complete the following information):**
 - iPad on iOS 14.6 Safari last version

**Additional context**
- Skin name:  JAGFx dashboard
- Dashboard version: 1.6.2
- SCS Telemetry version: 1.10.6

**Comment by JAGFx** [comment]
The next rest stop time will also be corrected

**Comment by sanekaze** [comment]
Thanx ! Do you know when this new version will be available to download ?

**Comment by JAGFx** [comment]
@sanekaze Maybe next week. I'm not sure.
