### ISSUE TITLE
The map is not at the correct angle, it has to rotate.

### ISSUE THREAD

**Issue by MorrisHutson** [JAGFx/ets2-dashboard-skin#72]
**Describe the bug**
When I try to use the Map, the screen is being like it has rotated. I mean, the map is not at the correct angle. Also, its angle always changes, sometimes it needs 90° rotation, sometimes nearly 180°, etc. 

**Expected behavior**
The map should be at the correct angle.

**Screenshots**
![map](https://user-images.githubusercontent.com/88095576/127334850-74d9d850-8e56-47ff-a117-30479c417c21.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 PRO 64-Bit
 - Browser: Google Chrome
 - Version: 92.0.4515.107 (for Google Chrome)

**Additional context**
- Skin name: Map
- Dashboard version: 1.6.2
- SCS Telemetry version: v1.16

**Comment by MorrisHutson** [comment]
As in addition; there is no support for "Road to Black Sea DLC". I forgot to write it.

**Comment by JAGFx** [comment]
@MorrisHutson Hi,

I can't find your issue or I don't correctly understand it. I've been trying on Base map, DLC map, on UK and Spain. All be fine.
It's correct (currently) to have the city name in rotation. The map are a giant picture splited on square. The cities and others elements are generated once. So the city name doesn't follow your player rotation but the giant map rotation.

The following is a [normal behavior](https://celestin.jagfx.fr/s/kA2PJ6GmCxyiqAt). The map rotate around the player. The player icon stay fixed

This is an [other possibility](https://celestin.jagfx.fr/s/eWAJk398WMEZrLZ). The map move but doesn't rotate. The player icon rotate.

If you can give other information to reproduce this issue. Thanks ;)

**Comment by MorrisHutson** [comment]
Hello again,

I am sending 2 more screenshots to make clear my situation for you. In the
screenshots. The map can rotate around the player or it can move but does
not rotate. Both of them are good for me. But, as you can see in the
screenshots, I do not want to rotate the Map actually, I have to rotate the
google page maybe. I mean, your application's interface is at the correct
position but the map is not. If you more information, you can write again
and again :) Also, you can write me from your discord server, it will be
easier and faster to see and answer for me.

SMITH Emmanuel ***@***.***>, 1 Ağu 2021 Paz, 18:05 tarihinde
şunu yazdı:

**Comment by JAGFx** [comment]
Hi

I read that you've got this issue when you set the active map to ETS2 base map (FULL DLC) So I'll check with this setting if i'm found an issue.
But I think your thinking is to get  the map like is shown on ETS or ATS (with UK shown and keep at the top left, with Spain shown and keep at the bottom left, Russia shown and keep  at the top right and Turkey shown and keep at the bottom right) this is a feature that can be enabled. It's the map rotation ( or north lock if you prefer) Click on the second button on the bottom right (under the information button). By default, the map rotation is enable (or the north lock is disabled).

So, that you think as an issue isn't it and that you think as a normal behavior isn't it too. I'm working on the issue with the ETS2 base map (FULL DLC) active map enabled and I'm gonna back to you.

**Comment by JAGFx** [comment]
I've added an option to enable on the map load the map rotation
