### ISSUE TITLE
Truck speed display is wrong

### ISSUE THREAD

**Issue by sanekaze** [JAGFx/ets2-dashboard-skin#75]
**Describe the bug**
The speed displayed does not match that of the truck.
Scania 12 + 2 in automatic, and automatic adjustment in the dashboard, 3rd gear on the truck but D5 is displayed.

**Expected behavior**
that the truck displays from C1 to 12 depending on the gear engaged

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
iPad on iOS 14.6 Safari last version

**Additional context**
Skin name: JAGFx dashboard
Dashboard version: 1.6.2
SCS Telemetry version: 1.10.6
Node14

**Comment by JAGFx** [comment]
@sanekaze Can you tell me if this issue are in all truck not?
If not, witch one?

**Comment by sanekaze** [comment]
I use a Scania in 12 + 2
A1 = D3 on the dashboard, up to D14 instead of A12

Same thing on a Volvo which can also be configured in 12 + 2

On a Mercedes which is in 12 or 16, it displays D6 instead of A6 but the speed is good.

But on my scania in 12 + 2, if I set manual gearbox in the commands and the dashboard remains in automatic instead of H-shifter, the speeds are displayed correctly
