### ISSUE TITLE
Skin edit/translation. 

### ISSUE THREAD

**Issue by Ativ3k** [JAGFx/ets2-dashboard-skin#80]
Adding skin translations as a text file? Eg ENG.js or ENG.txt.
Or after the decimal point:
WORD: "ENG = X, RU = X, PL = X"
E.g:
Truck: "ENG = Truck, RU = Грузовая машина, PL = Ciężarówka"

**Comment by JAGFx** [comment]
@Ativ3k Hi, this feature is already planned. See the #51 issue ;) 

Thanks for your interest in this project.
