### ISSUE TITLE
Map Skin - Bottom Bar Height Breaks

### ISSUE THREAD

**Issue by killer2239** [JAGFx/ets2-dashboard-skin#94]
**Describe the bug**

On the map dashboard, the bottom bars height breaks when speed enters 3 digits or Gears hit 10+. The screenshot shows when the gear is 10+ which is the most common to break it. This happens with both ETS2 and ATS.

**Expected behavior**

Bottom line should stay even.

**Screenshots**

![20220104_065704](https://user-images.githubusercontent.com/1090688/148544332-f8bf4f37-8985-4a15-848f-8f92fcea8f66.jpg)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Chrome
 - Version 97

**Smartphone (please complete the following information):**

 - Device: iPad 6th gen I think
 - OS: iOS 15
 - Browser: Stock Safari and latest Chrome from app store

**Additional context**

- Skin name: Map
- Dashboard version: [e.g. v1.6.7]
- SCS Telemetry version: Latest from install instructions

**Comment by JAGFx** [comment]
It's seem that is already fixed. Available on the next release.
